### ISSUE TITLE
problems with v1.0.1

### ISSUE THREAD

**Issue by gijzelaerr** [astromatic/visiomatic#2]
while following the instructions here:

http://www.visiomatic.org/software/visiomatic

I run into troubles while using visiomatic v1.0.0. The javascript error console gives:

```
TypeError: undefined is not an object (evaluating 'L.Canvas.instance')
TypeError: null is not an object (evaluating 'this._url.match(/^.*\/(.*)\..*$/)[1]')
```

browser: safari 8.0.2, OSX

**Comment by ebertin** [comment]
This should run fine now. Closing this.
